- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/crossfire_test.go
- appinterface/projection/crossfire/httpclient.go
- appinterface/projection/crossfire/httpclient_test.go
- cmd/chain-indexing/config.go
- cmd/chain-indexing/projections.go
- config/config.sample.toml
Add get participants JSON with unit test.
> Feat: add httpclient to get latest participants json

- appinterface/cosmosapp/client.go
- appinterface/projection/account/account.go
- appinterface/projection/account/view/account.go
- cmd/chain-indexing/app.go
- cmd/chain-indexing/httpapiserver.go
- cmd/chain-indexing/projections.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/accounts.go
- infrastructure/httpapi/routes/routes.go
- migrations/20201214121738_view_accounts.down.sql
- migrations/20201214121738_view_accounts.up.sql
Solution: add account projection
for balance, account number, used roc to fetch info
now all accounts used in blockchain are indexed and queried
and balance, account number is correct
> Problem: Missing account projections (fix #98)

- README.md
- pgmigrate.sh
- util/checkpassword.go
Solution: add password check for Postgres
> Problem: missing PASSWORD check (fix #265)

- appinterface/projection/crossfire/constants/db_keys.go
- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/crossfire_test.go
> Problem: Task Network Upgrade support

- appinterface/projection/crossfire/constants/db_keys.go
- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/crossfire_test.go
- appinterface/projection/crossfire/rank_commitment_test.go
- appinterface/projection/crossfire/test/participants.go
- appinterface/projection/crossfire/view/crossfire_chain_stats_test.go
- appinterface/projection/crossfire/view/crossfire_validators.go
- appinterface/projection/crossfire/view/crossfire_validators_stats_test.go
> Feat: add computeCommitmentRank for two commitment ranking

- internal/tmcosmosutils/tmpubkey.go
- internal/tmcosmosutils/tmpubkey_test.go
Solution: (Fix #281) Add the function in tmcosmosutils
> Problem: Missing conversion function from pubkey to account address

- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/rank_commitment_test.go
Disable taskActive and commitment ranking for the validator who missed taskSetup, resolved #284
> Feat: amend activeness logic for activeness

- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/crossfire_test.go
- appinterface/projection/crossfire/httpclient_test.go
- appinterface/projection/crossfire/rank_commitment_test.go
- cmd/chain-indexing/httpapiserver.go
- cmd/chain-indexing/projections.go
- go.sum
- infrastructure/httpapi/handlers/crossfire.go
- infrastructure/httpapi/routes/routes.go
- internal/tmcosmosutils/tmpubkey.go
- internal/tmcosmosutils/tmpubkey_test.go
> Problem: Crossfire API Handler

- infrastructure/httpapi/handlers/crossfire.go
Problem: Crossfire HTTP Handler - Bugfix Issue #290
Fixes #290 
The latest Bugfix returns the result below format:
`{
"result": [
{
"operatorAddress": "tcrocncl197ujxhaeyyv309f39c0s2gn0af0pps5pcxsr0a",
"initialDelegatorAddress": "tcro197ujxhaeyyv309f39c0s2gn0af0pps5pden6h7",
"moniker": "node1",
"taskSetup": "Completed",
"taskKeepActive": "Incompleted",
"taskProposalVote": "Incompleted",
"taskNetworkUpgrade": "Incompleted",
"rankPhase1n2CommitmentRank": 1,
"rankPhase3CommitmentRank": 0,
"rankTxSentRank": 0,
"stats": {
"totalTxSent": 0,
"txSentPhase1": 0,
"txSentPhase2": 0,
"txSentPhase3": 0,
"commitCountPhase1n2": 986,
"commitCountPhase2": 0,
"commitCountPhase3": 0,
"joinedAtBlockHeight": 0,
"joinedAtTimestamp": "1970-01-01T00:00:00Z"
}
},
{
"operatorAddress": …
> Problem: Crossfire HTTP Handler - Bugfix Issue #290

- appinterface/cosmosapp/client.go
- go.mod
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/accounts.go
- migrations/20201214121738_view_accounts.up.sql
- pgmigrate.sh
- projection/account/account.go
- projection/account/view/accounts.go
Solution: (Fix #285) Refactor projection and introduce proper types for Account API
> Problem: Account projection halts when account has no pub key recorded

- appinterface/projection/crossfire/constants/db_keys.go
- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/crossfire_test.go
- appinterface/projection/crossfire/httpclient_test.go
- appinterface/projection/crossfire/rank_commitment_test.go
- cmd/chain-indexing/config.go
- cmd/chain-indexing/projections.go
- config/config.sample.toml
- infrastructure/httpapi/handlers/crossfire.go
- projection/projections.go
- Weekly Count Support
- Jackpot Counts added in HTTP Handler
Fixes #296
> Problem: Missing Jackpot Weekly Count Support

- migrations/20201217193434_view_account_messages.up.sql
Solution: (Fix #302) Remove unique constraint
> Problem: Account message unique contraint does not work for same transaction broadcasted multiple times

- appinterface/cosmosapp/client.go
- infrastructure/httpapi/handlers/search.go
- projection/block/view/blocks.go
Solution: (Fix #306) Update http response struct
> Problem: Validator API token is always 0

- infrastructure/httpapi/handlers/status.go
- projection/validatorstats/validatorstats.go
- projection/validatorstats/validatorstats_test.go
- usecase/coin/dec_coin.go
Solution: (Fix #308) Encode in JSON
> Problem: Total Delegated and Reward Distributed is not in JSON

- entity/projection/manager.go
- migrations/20210113113838_view_account_transactions.up.sql
- migrations/20210113114120_view_account_transaction_data.up.sql
- projection/account_transaction/view/account_transaction_data.go
- projection/account_transaction/view/account_transactions.go
- projection/blockevent/view/blockevents.go
- projection/transaction/view/transactions.go
Solution: (Fix #310) Limit row insertions per write
> Problem: InsertAll may exceed postgres parameter limit

- migrations/20210120021440_view_transactions_block_height_desc_id_btree_index.down.sql
- migrations/20210120021440_view_transactions_block_height_desc_id_btree_index.up.sql
Solution: (Fix #312) add index to view_blocks table
> Problem: Blocks view list query is not optimizied

- cmd/chain-indexing/config.go
- cmd/chain-indexing/httpapiserver.go
- config/config.sample.toml
- infrastructure/httpapi/server.go
Solution: (Fix #316) Add pprof support to HTTP server
> Problem: Problem: Missing pprof support

- cmd/chain-indexing/config.go
- cmd/chain-indexing/httpapiserver.go
- config/config.sample.toml
Solution: create another port for pprof
> Problem: (fix #320)Missing pprof support for different port

- cmd/chain-indexing/config.go
- cmd/chain-indexing/httpapiserver.go
- config/config.sample.toml
Solution: add fix path for pprof
> Problem: (fix #322)pprof do not accept customized path

- usecase/parser/transaction.go
- usecase/parser/transaction_test.go
- usecase/parser/txdecoder.go
Solution: (Fix #326) Add threshold as int back
> Problem: MultiSig threshold is missing

- cmd/find-jackpot-winners/main.go
```
go run cmd/find-jackpot-winners/* [block-height] [output-file]
```
> Add Crossfire jackpot winner finder

- cmd/chain-indexing/syncmanager.go
Solution: (Fix #330) update sync manager logic
> Problem: SyncManager does not sync to the latest block

- appinterface/projection/view/total.go
- infrastructure/httpapi/handlers/blocks.go
- infrastructure/httpapi/handlers/validators.go
- infrastructure/httpapi/routes/routes.go
- migrations/20210125171426_view_validators_add_tendermint_pubkey_address.down.sql
- migrations/20210125171426_view_validators_add_tendermint_pubkey_address.up.sql
- migrations/20210125202339_view_validators_drop_unbonding_columns.down.sql
- migrations/20210125202339_view_validators_drop_unbonding_columns.up.sql
- migrations/20210125232317_view_validator_block_commitments.down.sql
- migrations/20210125232317_view_validator_block_commitments.up.sql
- migrations/20210126004127_view_validator_block_commitments_block_height_btree_index.down.sql
- migrations/20210126004127_view_validator_block_commitments_block_height_btree_index.up.sql
- migrations/20210126005946_view_validator_block_commitments_total.down.sql
- migrations/20210126005946_view_validator_block_commitments_total.up.sql
- projection/validator/validator.go
- projection/validator/validator_test.go
- projection/validator/view/validator_block_commitments.go
- projection/validator/view/validator_block_commitments_total.go
- projection/validator/view/validators.go
Solution: (Fix #332) Add to validator projection
> Problem: Missing validator block commitments in projection

- appinterface/projection/crossfire/crossfire.go
- appinterface/projection/crossfire/view/crossfire_validators_stats.go
This is just a removal of dirty LIKE command done in crossfire HTTP handler.
> Optimisation FindAllLike style

- appinterface/event/rdbstore.go
- cmd/chain-indexing/indexservice.go
- cmd/chain-indexing/syncmanager.go
- infrastructure/pg/pgx.go
- projection/account/view/accounts.go
- projection/account_message/view/account_messages.go
- projection/account_transaction/view/account_transactions.go
- projection/block/view/blocks.go
- projection/blockevent/view/blockevents.go
- projection/transaction/view/transactions.go
- projection/validator/view/validator_activities.go
- projection/validator/view/validator_block_commitments.go
- projection/validator/view/validators.go
Solution: (Fix #339) Close rows on function completes
> Problem: Potential memory leak on DB rows scanning

- config/config.sample.toml
- migrations/20210127194322_view_account_transaction_data_block_height_hash_btree_index.down.sql
- migrations/20210127194322_view_account_transaction_data_block_height_hash_btree_index.up.sql
- projection/account_transaction/view/account_transactions.go
Fix #338 
Add index to account transaction
> Problem: performance degrade when account transactions table grows

- migrations/20210130232207_view_validator_activities_operator_address_block_height_btree_index.down.sql
- migrations/20210130232207_view_validator_activities_operator_address_block_height_btree_index.up.sql
- migrations/20210130232708_view_validator_activities_drop_operator_address_btree_index.down.sql
- migrations/20210130232708_view_validator_activities_drop_operator_address_btree_index.up.sql
Solution: (Fix #342) Replace operator address index with operator address and block height index
> Problem: Validator activities API degrades when table grows

- appinterface/cosmosapp/client.go
- cmd/chain-indexing/httpapiserver.go
- infrastructure/cosmosapp/commission.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/accounts.go
- internal/tmcosmosutils/tmpubkey.go
- internal/tmcosmosutils/tmpubkey_test.go
- projection/account_transaction/account_transaction.go
- projection/account_transaction/view/account_transactions.go
Solution: (Fix #345) Add balances back
> Problem: Missing balance and commission in account API

- appinterface/cosmosapp/client.go
- infrastructure/cosmosapp/delegation.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/accounts.go
Solution: properlty handle delegation not found error
> Problem: Account API returns internal server error

- usecase/parser/begin_block_events.go
- usecase/parser/begin_block_events_test.go
- usecase/parser/test/begin_block_slash_event.go
Solution: remove no longer existing Attribute key for slash event
> Problem: (fix #351) cosmos-sdk v0.41.0 introduce breaking in slash event

- migrations/20210225161055_view_account_messages_account_btree_index.down.sql
- migrations/20210225161055_view_account_messages_account_btree_index.up.sql
- migrations/20210225161111_view_account_messages_account_message_type_btree_index.down.sql
- migrations/20210225161111_view_account_messages_account_message_type_btree_index.up.sql
- migrations/20210225163350_view_account_messages_account_message_type_id_btree_index.down.sql
- migrations/20210225163350_view_account_messages_account_message_type_id_btree_index.up.sql
- migrations/20210225163402_view_account_messages_account_id_btree_index.down.sql
- migrations/20210225163402_view_account_messages_account_id_btree_index.up.sql
Solution: (Fix #362) Add DB index
> Problem: Account message API is not optimized

- infrastructure/tendermint/httpclient_test.go
- infrastructure/tendermint/test/genesis_genutils_mixed_number_and_string.go
- usecase/model/genesis/genesis.go
Solution: (Fix #366) Use interface{} to parse numeric fields in gentx
> Problem: Cannot parse genesis using numbers in numeric fields

- go.mod
- go.sum
Solution: (Fix #368) Add support
> Problem: Missing IBC transfer parsing support

- check-db-password-strength.sh
- infrastructure/httpapi/handlers/validators.go
- pgmigrate.sh
Solution: (Fix #371) Return BadRequest if address is invalid
> Problem: Validator API returns the last validator if provided with incorrect address

- cmd/chain-indexing/projections.go
- config/config.sample.toml
- infrastructure/httpapi/handlers/status.go
- migrations/20210408183931_create_chain_stats.down.sql
- migrations/20210408183931_create_chain_stats.up.sql
- projection/chainstats/chainstats.go
- projection/chainstats/chainstats_suite_test.go
- projection/chainstats/chainstats_test.go
- projection/chainstats/view/chainstats.go
- projection/projections.go
Solution: (Fix #374) Add block time projection and API
> Problem: Missing average block time

- appinterface/cosmosapp/client.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/accounts.go
Solution: (Fix #376) escape next key in url
> Problem: Cosmos API client does not escape next key properly

- internal/utctime/utctime.go
- projection/chainstats/chainstats.go
- projection/chainstats/chainstats_test.go
Solution: (Fix #378) change to use RFC3339
> Problem: ChainStats failed to parse some time formats

- appinterface/projection/rdbparambase/param.go
- appinterface/projection/rdbparambase/types/param.go
- appinterface/projection/rdbparambase/view/params.go
- usecase/model/genesis/genesis.go
Solution: (Fix #381) Add param base projection
> Problem: Missing network params projection

- appinterface/cosmosapp/account.go
- appinterface/cosmosapp/pubkey.go
- appinterface/cosmosapp/validator.go
Solution: (Fix #384) Fix cosmos http client parsing error
> Problem: token from validator API is always 0

- appinterface/cosmosapp/client.go
- cmd/chain-indexing/httpapiserver.go
- infrastructure/cosmosapp/annual_privisions.go
- infrastructure/cosmosapp/delegation.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/cosmosapp/validator.go
- infrastructure/httpapi/handlers/status.go
- infrastructure/httpapi/handlers/validators.go
- projection/validator/view/validators.go
Solution: (Fix #388) Add APY and commission sorting
> Problem: Missing APY and commission sorting

- config/config.testnet.toml
- infrastructure/httpapi/handlers/proposals.go
- projection/proposal/view/votes.go
Solution: Handle inactive proposal properly
> Problem: Proposal API returns 500

- projection/validator/validator_activity.go
Solution: (Fix #373) Fix incorrect total incremented
> Problem: Incorrect pagination in validator activities API

- infrastructure/httpapi/handlers/nfts.go
- infrastructure/httpapi/routes/routes.go
- projection/nft/nft.go
- projection/nft/view/tokens.go
Solution: (Fix #418) fix projection and API
> Problem: NFT projection may panic on burn

- infrastructure/httpapi/handlers/nfts.go
Solution: (Fix #424) Fix incorrect filtering message type
> Problem: NFT transfer API returns empty result

- projection/nft/nft.go
Solution: (Fix #426) Handle edit history
> Problem: NFT edit history is ignored

- migrations/20210620161041_alter_view_nft_tokens_add_block_height.down.sql
- migrations/20210620161041_alter_view_nft_tokens_add_block_height.up.sql
- migrations/20210620161119_alter_view_nft_denoms_add_block_height.down.sql
- migrations/20210620161119_alter_view_nft_denoms_add_block_height.up.sql
- migrations/20210621123820_alter_view_nft_tokens_drop_burned.down.sql
- migrations/20210621123820_alter_view_nft_tokens_drop_burned.up.sql
- projection/nft/nft.go
- projection/nft/view/denoms.go
- projection/nft/view/messages.go
- projection/nft/view/tokens.go
- projection/projections.go
Solution: (Fix #429) remove burnt NFT
> Problem: NFT cannot be re-minted after burn

- infrastructure/httpapi/handlers/nfts.go
- projection/nft/view/tokens.go
Solution: (Fix #436) Add sort by last edited option
> Problem: Missing last edited sorting in NFT token list API

- infrastructure/httpapi/handlers/nfts.go
- migrations/20210708050955_alter_view_nft_tokens_add_last_transferred_at.down.sql
- migrations/20210708050955_alter_view_nft_tokens_add_last_transferred_at.up.sql
- projection/nft/nft.go
- projection/nft/view/tokens.go
Solution: (Fix #441) Add support
> Problem: Missing last_transferred_at support in NFT API

- cmd/chain-indexing/httpapiserver.go
- infrastructure/httpapi/handlers/validators.go
Sotlution: (Fix #448) Use estimated block count for better APY estimation
> Problem: Validator APY is not accurate

- README.md
Added some reminders on the readme.
> Updated root readme

- usecase/event/minted.go
- usecase/event/minted_test.go
- usecase/model/mint_params.go
- usecase/parser/begin_block_events.go
- usecase/parser/begin_block_events_test.go
> Change Minted event AnnualProvisions to coins format

- cmd/chain-indexing/app.go
- cmd/chain-indexing/indexservice.go
Solution: resolved #370 by add a new config option
> Problem: Missing read only mode

- usecase/event/msgdelegate.go
- usecase/event/msgdelegate_test.go
- usecase/model/msgdelegate.go
- usecase/parser/msg.go
- usecase/parser/msgdelegate_test.go
Solution: fixed #428 by adding AutoClaimedRewards field to MsgDelegate
> Problem: Missing MsgDelegate auto claimed rewards

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- README.md
resolves #155 
includes PR #446
> Add Dockerfile

- Dockerfile
- Makefile
- pgmigrate.sh
Solution: (Fix #468) Update script to install migrate based on Golang version
> Problem: pgmigrate.sh failed to install migrate under Golang v1.15 or below

- cmd/chain-indexing/syncmanager.go
- go.mod
- go.sum
- infrastructure/feed/chain/blockheighttracker.go
Solution: (Fix #474) Use exponential backoff to retry HTTP request on sync
> Problem: Wasting resource to retry on network error

- config/config.localnet.toml
- config/config.mainnet.toml
- config/config.sample.toml
- config/config.testnet-3.toml
- config/config.testnet.toml
- go.mod
- go.sum
- internal/json/json_suite_test.go
- internal/json/uint16.go
- internal/json/uint16_test.go
- internal/json/uint64.go
- internal/json/uint64_test.go
- usecase/command/create_genesis.go
- usecase/event/msg_ibc_acknowledgement_test.go
- usecase/event/msg_ibc_recv_packet_test.go
- usecase/model/genesis/genesis.go
- usecase/model/ibc/ibc.go
- usecase/parser/ibcmsg/ibcmsg.go
- usecase/parser/ibcmsg/mapstructure.go
- usecase/parser/test/tx_msg_ibc_recv_packet_solomachine.go
Problem: Missing support to SoloMachine IBC transfer
Problem: json.Number will marshal to number but not string
Solution: (Fix #487) (Fix #488) Add custom json number types and support SoloMachine IBC transfer
> Problem: Missing support to SoloMachine IBC transfer and json.Number will marshal to number but not string

- usecase/parser/ibcmsg/ibcmsg.go
Solution: (Fix #499) Use packet data to extract the refund content
> Problem: Timeout event data maybe missing in MsgTimeout and MsgTimeoutOnClose

- projection/ibc_channel/ibc_channel.go
- usecase/model/ibc/localhost.go
- usecase/model/ibc/msg_create_client.go
- usecase/model/ibc/msg_update_client.go
- usecase/model/ibc/solomachine.go
- usecase/parser/ibcmsg/ibcmsg.go
- usecase/parser/msg.go
- usecase/parser/msg_ibc_create_solomachine_client_test.go
- usecase/parser/msg_ibc_create_tendermint_client_test.go
- usecase/parser/msg_ibc_update_tendermint_client_test.go
- usecase/parser/test/tx_msg_ibc_create_solomachine_client.go
- usecase/parser/test/tx_msg_ibc_create_tendermint_client.go
- usecase/parser/test/tx_msg_ibc_tendermint_update_client.go
Solution: ( fixed #502 ) add create client and update client message parser
> Problem: Missing create solo machine client parser

- usecase/parser/msg.go
- usecase/parser/msg_exec_test.go
- usecase/parser/test/tx_msg_exec_msg_delegate.go
- usecase/parser/test/tx_msg_exec_msg_send.go
- usecase/parser/utils/parsermanager.go
> Problem: missing logic to parse MsgExec internal messages

- projection/account_message/account_message.go
- projection/account_transaction/account_transaction.go
- usecase/parser/msg.go
- usecase/parser/msg_exec_test.go
- usecase/parser/test/tx_msg_exec_msg_delegate.go
- usecase/parser/test/tx_msg_exec_msg_send.go
- usecase/parser/utils/parsermanager.go
Solution: fixed #527 
Added new events to `AccountMessage` and `AccountTransaction` projections
> Problem: new events missing in projection

- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity.go
Solution: (Fix #554) Fix incorrect listening events
> Problem: Cronos Bridge Pending Activity is missing MsgTimeout

- go.mod
- go.sum
Solution: (Fix #558) Upgrade cronos dependency to latest version
> Problem: Tx Decoder cannot recognize latest Cronos transactions

- infrastructure/httpapi/handlers/bridges.go
- projection/bridge_activity/view/bridge_activities.go
Solution: (Fix #573) Add greater than filter
> Problem: Bridge Activities API missing id and time filter

- external/utctime/utctime.go
Solution: (Fix #581) Add accessors
> Problem: Missing accessor in utctime

- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity.go
- projection/bridge_activity/types/types.go
Solution: fixed #583 
Changes:
- Updated the logic when handling MsgRecvPacket
- Added an extra status
> Problem: missing logic to handle already relayed MsgRecvPacket in BridgePendingActivity

- projection/proposal/view/proposals.go
Update proposal list to sort by numeric id
> Update proposal list sorting

- infrastructure/httpapi/handlers/bridges.go
- projection/bridge_activity/bridge_activity_matcher/migrations/20211110130600_update_view_ bridge_activities_status_failed_to_failed_on_chain.down.sql
- projection/bridge_activity/bridge_activity_matcher/migrations/20211110130600_update_view_ bridge_activities_status_failed_to_failed_on_chain.up.sql
- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity.go
- projection/bridge_activity/types/types.go
Solution: (Fix #604) Change fail status to FailedOnChain
> Problem: Bridge Activities fail status should be FailedOnChain but not Failed

- projection/bridge_activity/bridge_activity_matcher/migrations/20211110130600_update_view_ bridge_activities_status_failed_to_failed_on_chain.down.sql
- projection/bridge_activity/bridge_activity_matcher/migrations/20211110130600_update_view_ bridge_activities_status_failed_to_failed_on_chain.up.sql
> Problem: Malformed bridge activity migration SQL

- appinterface/cosmosapp/client.go
- appinterface/cosmosapp/mockclient.go
- infrastructure/cosmosapp/httpclient.go
Solution: fix #629 
Remvoed `BalanceByDenom()` related code.
> Problem: API breaking change in CosmosSDK 0.44.4

- appinterface/eventhandler/handler.go
- appinterface/eventhandler/projection.go
- appinterface/eventhandler/rdbeventstore.go
- bootstrap/app.go
- bootstrap/config.go
- bootstrap/syncmanager.go
- entity/projection/manager.go
- go.mod
- infrastructure/metric/prometheus/http.go
- infrastructure/metric/prometheus/projection_exec_time.go
- infrastructure/metric/prometheus/projection_latest_block.go
- infrastructure/metric/prometheus/prometheus.go
Resolved #638 
- Added config for prometheus server
- Added prometheus data point for projection latest height and execution time
Example exported data:
> Problem: Lack of real time performance monitoring integration interface

- appinterface/projection/rdbprojectionbase/base.go
- projection/account/account.go
- projection/bridge_activity/bridge_activity_matcher/bridge_activity_matcher.go
- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity.go
- usecase/projection/base.go
- usecase/projection/config.go
Solution: (Fix #648) Refactor projection to accept config directly
> Problem: Projection config is not flexible

- README.md
> Problem: Missing clear setup documentation

- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity.go
- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity_test.go
Solution: (Fix #641) Add multiple channel supports and test cases
> Problem: Bridge pending activity projection supports only one channel

- usecase/parser/msg_exec_test.go
- usecase/parser/register.go
Solution: (Fix #674) Disable MsgExec parser
> Problem: MsgExec parser can cause indexer to halt

- external/bridges/parsers/addresshook.go
- external/bridges/parsers/cronos/addresshook.go
- infrastructure/httpapi/handlers/bridges.go
- projection/bridge_activity/view/bridge_activities.go
- projection/bridge_activity/view/bridge_activities_mock.go
Solution: Accept config for dynamic API query
> Problem: Bridge activity API is not dynamic based on supported chain

- projection/account_transaction/account_transaction.go
- projection/transaction/transaction.go
- projection/transaction/transaction_test.go
- projection/transaction/view/transactions.go
- usecase/event/transaction_created_test.go
- usecase/event/transaction_failed_test.go
- usecase/model/transaction.go
- usecase/parser/authinfo.go
- usecase/parser/test/tx_signer_empty_pubkey.go
- usecase/parser/transaction.go
- usecase/parser/transaction_test.go
- usecase/parser/utils/txdecoder.go
Solution: Change transaction signer to null-able object
> Problem: Transaction signer could be empty

- infrastructure/httpapi/handlers/bridges.go
- projection/bridge_activity/view/bridge_activities.go
Solution: (Fix #687) Add new sorting and maintain backward-compatibility
> Problem: Bridge activity API does not support sorting by block times

- infrastructure/httpapi/handlers/account_messages.go
- infrastructure/httpapi/handlers/account_transactions.go
- infrastructure/httpapi/handlers/accounts.go
- infrastructure/httpapi/handlers/blockevents.go
- infrastructure/httpapi/handlers/blocks.go
- infrastructure/httpapi/handlers/bridges.go
- infrastructure/httpapi/handlers/guard.go
- infrastructure/httpapi/handlers/ibc_channel.go
- infrastructure/httpapi/handlers/ibc_channel_message.go
- infrastructure/httpapi/handlers/nfts.go
- infrastructure/httpapi/handlers/proposals.go
- infrastructure/httpapi/handlers/transactions.go
- infrastructure/httpapi/handlers/validators.go
Solution: (Fix #689) Add value existence check to all API handlers
> Problem: URL values in routes are missing existence check

- infrastructure/httpapi/handlers/bridges.go
- projection/bridge_activity/view/bridge_activities.go
Solution: (Fix #691) Update sort criteria behaviour and better BadRequest reasoning
> Problem: Bridge activities API params are confusing

- external/json/json.go
- external/json/json_test.go
- projection/account_message/view/account_messages.go
- projection/account_transaction/view/account_transaction_data.go
- projection/nft/view/messages.go
- projection/transaction/view/transactions.go
Solution: Escape NUL byte before insert to database
> Problem: unsupported Unicode escape sequence because of JSON NUL byte

- usecase/parser/utils/txdecoder.go
Solution: Add all IBC types on v1.2.1
> Problem: Missing some IBC transaction and proposal types

- usecase/parser/msg.go
Solution: Remove panic as a temporary fix
> Problem: Unrecognized governance proposal types should not panic

- .github/workflows/golangci-lint.yml
- usecase/parser/msg.go
Solution: Do no panic on invalid amount
> Problem: Parser may panic on invalid staking transactions

- external/tmcosmosutils/cosmoscoin.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/status.go
- usecase/coin/coin.go
- usecase/coin/coin_benchmark_test.go
- usecase/coin/coin_test.go
- usecase/coin/dec_coin.go
- usecase/coin/dec_coin_test.go
- usecase/coin/denom.go
- usecase/event/gravity_ethereum_send_to_cosmos_handled_test.go
- usecase/parser/end_block_events_ethereum_send_to_cosmos_handled_test.go
- usecase/parser/genesis.go
- usecase/parser/msg_begin_redelegate_test.go
- usecase/parser/msg_undelegate_test.go
Solution: Return error instead of panic
> Problem: Coin may panic on invalid coin input

- usecase/parser/block_results_txs_results.go
Solution: Remove an incorrect early break
> Problem: Cronos Send To IBC parsing may overlooked some valid message

- LICENSE
- example/app/example-app/run.go
> Problem: License file is not up-to-dated

- infrastructure/httpapi/handlers/validators.go
> Problem: Pointer dereference on validator FindBy endpoint

- projection/block/view/blocks.go
Solution: filter by hash only if the keyword is not a integer
> fix search view_blocks type error

- infrastructure/httpapi/handlers/account_raw_transactions.go
- projection/account_raw_transaction/account_raw_transaction.go
- projection/account_raw_transaction/account_raw_transaction_test.go
- projection/account_raw_transaction/migrations/20220920113838_view_account_raw_transactions.down.sql
- projection/account_raw_transaction/migrations/20220920113838_view_account_raw_transactions.up.sql
- projection/account_raw_transaction/migrations/20220920113839_view_account_raw_transactions_total.down.sql
- projection/account_raw_transaction/migrations/20220920113839_view_account_raw_transactions_total.up.sql
- projection/account_raw_transaction/view/account_raw_transactions.go
- projection/account_raw_transaction/view/account_raw_transactions_mock.go
- projection/account_raw_transaction/view/account_raw_transactions_total.go
- projection/account_raw_transaction/view/account_raw_transactions_total_mock.go
- projection/account_transaction/view/account_transactions.go
- usecase/parser/block.go
> Problem: Missing raw account transaction projection

- infrastructure/httpapi/handlers/health.go
> ADD: health check endpoint

- appinterface/cosmosapp/client.go
- appinterface/cosmosapp/mockclient.go
- infrastructure/cosmosapp/distribution.go
- infrastructure/cosmosapp/httpclient.go
- infrastructure/httpapi/handlers/validators.go
Solution: Update global estimated APY to include tax
> Problem: Validator APY calcuation does not consider community tax

- external/json/numeric_string.go
- projection/account_message/account_message_test.go
- projection/bridge_activity/bridge_pending_activity/bridge_pending_activity_test.go
- projection/ibc_channel/ibc_channel_test.go
- projection/ibc_channel_message/ibc_channel_message_test.go
- usecase/event/cronos_sent_to_ibc_created_test.go
- usecase/event/msg_ibc_timeout_on_close_test.go
- usecase/event/msg_ibc_timeout_test.go
- usecase/parser/block_results_txs_result_create_send_to_ibc_test.go
- update json.NumericString type to parse from big.Int
> Fix: amount json marshal int overflow

- usecase/parser/ibc/msg.go
- usecase/parser/msg.go
Parse messages related to:
- ibc connection
- ibc transfer
- ibc channel
> Feat: parse all ibc messages inside ethereum tx
