projection/transaction/view/transactions.go
Solution: (Fix #303) API returns the last transaction in DB
=> Problem: Transaction API return the first transaction with same hash

projection/validator/view/validator_activities.go
Solution: (Fix #328) Update rows affected logic
=> Problem: Validator activities may return false alarm when activities count exceed 500

projection/validator/view/validators.go
power and cumulative power in validators API is expressed in exponential notation
Solution: (Fix #403) Display as decimal without exponent
Problem: Validators API should sort Inactive before Unbonded validators
Solution: (Fix #406) Sort Inactive before Unbonded
=> Problem: power and cumulative power in validators API is expressed in exponential notation

migrations/20210805154736_alter_view_transactions_add_signer.down.sql, migrations/20210805154736_alter_view_transactions_add_signer.up.sql, projection/transaction/transaction.go, projection/transaction/view/transactions.go
Solution: fixed #438 by adding signers field into transaction struct
Modified response would be like:
```
{
"blockHeight": 13618,
"blockHash": "625B78B0C643021B9C917BFCC2E8CDE8F9A39341DFCB538EFB5A86ED26B5B87F",
...,
"signers": [
{
"type": "/cosmos.crypto.secp256k1.PubKey",
"isMultiSig": false,
"pubkeys": [
"Ah5t0VGq6AIcsvPYT1lYjKq6thZE3kpaPtbolj61vgcU"
],
"accountSequence": 3,
"address": "tcro1f5rds2xlqswhpxynp6v62k4kz328fxd00059w4"
}
]
}
```
=> Problem: Missing signers in transaction API

infrastructure/httpapi/handlers/validators.go, projection/account_transaction/view/account_transactions_total.go
Solution: Fixed #452. Calculate averageBlockTime using n latest blocks.
=> Problem: Missing estimated APY based on recent n blocks

pgmigrate.sh
Solution: (Fix #479) change to original directory after installation
=> Problem: pgmigrate script should not change directory after installing dependency

pgmigrate.sh
Solution: (Fix #484) Hide migrate command for security reason
=> Problem: Migrate command is printed on shell in pgmirate.sh

config/config.localnet.toml, config/config.mainnet.toml, config/config.sample.toml, config/config.testnet-3.toml, config/config.testnet-4.toml, config/config.testnet.toml, migrations/20210830173217_view_ibc_channel_messages.down.sql, migrations/20210830173217_view_ibc_channel_messages.up.sql, projection/ibc_channel/ibc_channel.go, projection/ibc_channel/view/ibc_channel_messages.go, projection/projections.go
Solution: fixed #509 
In config file, use `IBCChannelTxMsgTrace` projection instead of `IBCChannel` projection.
Table schema:
```
CREATE TABLE view_ibc_channel_messages (
id BIGSERIAL,
channel_id VARCHAR NOT NULL,
block_height BIGINT NOT NULL,
source_channel VARCHAR NOT NULL,
destination_channel VARCHAR NOT NULL,
denom VARCHAR NOT NULL,
amount VARCHAR NOT NULL,
success VARCHAR NOT NULL,
error VARCHAR NOT NULL,
message_type VARCHAR NOT NULL,
message JSONB NOT NULL,
updated_bonded_tokens JSONB NOT NULL,
PRIMARY KEY(id)
);
```
=> Problem: missing IBC channel debug projection

infrastructure/httpapi/handlers/ibc_channel.go, infrastructure/httpapi/routes/routes.go, migrations/20210902150815_view_ibc_denom_hash_mapping.down.sql, migrations/20210902150815_view_ibc_denom_hash_mapping.up.sql, projection/ibc_channel/ibc_channel.go, projection/ibc_channel/view/ibc_denom_hash_mapping.go, usecase/model/ibc/localhost.go, usecase/model/ibc/msg_create_client.go, usecase/model/ibc/msg_update_client.go, usecase/model/ibc/solomachine.go, usecase/parser/ibcmsg/ibcmsg.go, usecase/parser/msg.go, usecase/parser/msg_ibc_create_solomachine_client_test.go, usecase/parser/msg_ibc_create_tendermint_client_test.go, usecase/parser/msg_ibc_update_tendermint_client_test.go, usecase/parser/test/tx_msg_ibc_create_solomachine_client.go, usecase/parser/test/tx_msg_ibc_create_tendermint_client.go, usecase/parser/test/tx_msg_ibc_tendermint_update_client.go
Solution: fixed #490 
**This one is depended on PR #511 (ibc channel debug projection), please review that one first** 🙏 
- Introduced a new table, which contain two columns `denom` and `hash`
- Added a new API to fetch all denom-hash mappings. `/ibc/denom-hash-mappings`
```
{
"result": [
{
"denom": "transfer/channel-0/solotoken",
"hash": "1A35E932DCE61466ED9F72D0B436628C388FB1BC60CB23A055039B7DE54883CC"
},
{
"denom": "transfer/channel-1/USDC",
"hash": "C59CA0D4F324B119C79782232700A6920B2EACA776558D7319CFC36DEE5672BF"
},
{
"denom": "transfer/channel-2/USDC",
"hash": "21E9F91EE9AC1D7E2C3D002F4AA73CAAB61801B055FB6721D36F16BB890BE0A2"
},
{
"denom": "transfer/channel-1/TEST",
"hash": "96D929A2DDBAB720DA3AB084914A64D40920DCF8CCD06B32966FBAF3AE75BD24"
},
{
"denom": "transfer/channel-2/TEST", …
```
=> Problem: Missing IBC denom trace to hashed denom API

infrastructure/httpapi/handlers/ibc_channel.go, projection/ibc_channel/view/ibc_channels.go
Solution: fixed #514 
Provide optional query params for `ibc/channels`.
```
order= lastActivityBlockHeight.asc
order= lastActivityBlockHeight.desc ------> default sorting
order= createdAtBlockTime.asc
order= createdAtBlockTime.desc
status=true
status=false
```
=> Problem: missing created_at_block_time and last_activity_block_time sorting params for ibc channel list API

projection/ibc_channel/ibc_channel.go, projection/ibc_channel/ibc_channel_test.go, usecase/model/ibc/msg_transfer.go, usecase/parser/ibcmsg/ibcmsg.go, usecase/parser/msg_ibc_transfer_transfer_test.go
Solution: fixed #529 
The previous `MsgTransferParams.Token.Denom` is possible in format of `ibc/sha256(xxx)`.
In order to get the human-readable denom string, I added logic to parse `packet_data` field from `send_packet` block event.
So now, `MsgTransferParams.PacketData.Denom` is always a human-readable denom string. For example: `basecro` or `transfer/channel-0/basecro`.
Use `denom`, `packetSourcePort`, `packetSourceChannel` to check if receiver chain is the token source.
If denom starts with `packetSourcePort/packetSourceChannel`, then the receiver chain is the token source.
1. `MsgTransfer` will update `BondedTokens`
2. `MsgRecvPacket` will update `BondedTokens`
3. `MsgAcknowledgement` success, do nothing
4. `MsgAcknowledgement` failure (contains error), revert what is done in …
=> Problem: update ibc channel projection based on findings

infrastructure/httpapi/handlers/bridges.go
Solution: (Fix #591) Support both sourceBlockHeight and sourceBlockTime
=> Problem: bridge list tx APIs have inconsistent source block order param

projection/ibc_channel/ibc_channel.go, projection/ibc_channel/ibc_channel_test.go, projection/ibc_channel/migrations/20211109173428_alter_view_ibc_channels_columns.down.sql, projection/ibc_channel/migrations/20211109173428_alter_view_ibc_channels_columns.up.sql, projection/ibc_channel/view/ibc_channels.go, projection/ibc_channel/view/ibc_channels_mock.go
Solution: fixed #590 
- Renamed ibc_channel table columns `total_transfer_*` to `total_relay_*`.
- Success rate now indicates the ratio of successfully relayed `IBC Transfer`
- Updated related test cases
If you want to test newly added migration script, you will need to update `MIGRATION_GITHUB_TARGET`.
First, you need to pushed your code to a branch, then change the const:
`MIGRATION_GITHUB_TARGET = "github://%s:%s@crypto-com/chain-indexing/%s#<YOUR_BRANCH_NAME>"`
For example, to test this branch locally, you will need to change it to:
`MIGRATION_GITHUB_TARGET = "github://%s:%s@crypto-com/chain-indexing/%s#fix/590-relay-out-success-rate"`
=> Problem: Current logic of "failed IBC transfer" maybe inaccurate

projection/ibc_channel_message/ibc_channel_message.go, projection/ibc_channel_message/ibc_channel_message_test.go
Solution: fix #646 
Details are in the issue description.
=> Problem: IBC Transfer Message denom not in fixed format

go.mod, go.sum
Solution: fix #661 
Replace the vulnerable package path with `github.com/scrtlabs/btcutil`.
=> Problem: the package btcutil need to be upgraded

usecase/parser/msg.go
Solution: (Fix #674) Disable MsgExec command at blocker tx parser
=> Problem: MsgExec parser can cause indexer to halt

projection/nft/migrations/20221101171151_alter_view_nft_tokens_drop_constraint.down.sql, projection/nft/migrations/20221101171151_alter_view_nft_tokens_drop_constraint.up.sql
The same `denom_id` and `token_id`on burned NFT will be used for minting a new NFT. To avoid the database unique key conflict, we use `upsert` NFT token ( update with condition `burned = true`) instead of `insert` on `MsgNFTMintNFT` event.
=> Fix: resolve duplicate NFT tokens with upsert

usecase/parser/ibcmsg/ibcmsg.go, usecase/parser/utils/txs_results_log_event.go
Since the events in `MsgAcknowledgement` in type `acknowledge_packet` are duplicated, the code will get the last events.
Example:
```
{
"type": "send_packet",
"attributes": [
{
"key": "packet_data",
"value": "{"amount":"4975060000","denom":"transfer/channel-0/basetcro","receiver":"tcro1q3aradsw9nldnnkna42dfmtakg8hxdcuvz7zhe","sender":"tcrc1k480peuqy544gcfqd0rnaxq7g002633j2rk8cj"}"
},
{
"key": "packet_data_hex",
"value": "7b22616d6f756e74223a2234393735303630303030222c2264656e6f6d223a227472616e736665722f6368616e6e656c2d302f626173657463726f222c227265636569766572223a227463726f317133617261647377396e6c646e6e6b6e61343264666d74616b67386878646375767a377a6865222c2273656e646572223a2274637263316b3438307065757179353434676366716430726e61787137673030323633336a32726b38636a227d"
},
{
"key": …
```
=> Problem: duplicate attribute key on IBC MsgAcknowledgement

usecase/parser/ibc/msg.go
`panic: panic when parsing block at height 13123448: missing `timeout_packet` event in TxsResult log`
Got empty `timeout_packet` in `msg_index=1` log
https://rest.mainnet.crypto.org/cosmos/tx/v1beta1/txs/1865B4678750DD77E1834BA78A5FCAE4D827B91DA101C4BBB6492793038D4CA7
IBC transfer refunded in [DD7E643082DC29337CFC09D033A509D1EF4D0693DFD0C483CE4D1C0147B00A60](https://www.mintscan.io/crypto-org/transactions/DD7E643082DC29337CFC09D033A509D1EF4D0693DFD0C483CE4D1C0147B00A60)
but show in [1865B4678750DD77E1834BA78A5FCAE4D827B91DA101C4BBB6492793038D4CA7](https://www.mintscan.io/crypto-org/transactions/1865B4678750DD77E1834BA78A5FCAE4D827B91DA101C4BBB6492793038D4CA7) too with empty `timeout_packet`
The refund data
```
{
"amount": "300000000",
"denom": "basecro",
"receiver": …
```
=> Fix: Return empty command instead of panic for empty ibc timeout_packet

usecase/parser/icaauth/msg.go, usecase/parser/msg.go, usecase/parser/utils/parsermanager.go
- use `IsEvmInnerMsg` in msg parser to separate current and evm tx msg parsing.
- parse ICA msgRegisterAccount by checking `channel_open_init` event
- parse ICA msgSubmitTx by checking `submit_msgs_result` event (do not need to parse the inner msg, it will execute on the host chain rather than controller chain).
=> Chain Indexing: parse IBC and ICA message on EVM transaction

usecase/parser/ibc/msg.go, usecase/parser/msg.go
Issue
- Ibc transfer emits more than one `send_packet` event inside etherum tx and got panic
Solution
- use `GetEventsByType` instead of `GetEventByType` to loop through the events
=> Fix: ibc transfer parsing inside eth tx

usecase/parser/gov/v1/msg.go
Proposal with msg `/cosmos.consensus.v1.MsgUpdateParams`: http://internal-testnet2-cronos-internal-fn-alb-1137839070.ap-southeast-1.elb.amazonaws.com:1317/cosmos/gov/v1beta1/proposals/29
=> Fix: skip msg cosmos.consensus.v1.MsgUpdateParams in submit proposal parser
